version: "3.8"
services:
  mongo:
    image: mongo
    volumes:
      - mongoData:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - ${MONGO_PORT}:${MONGO_PORT} 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL="mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017"

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT} 
  
volumes:
   mongoData: