version: "3.8"
services:
  mongo:
    image: mongo
    volumes:
      - mongoData:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL="mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017"

  redis:
    image: redis:alpine

  app:
    build: .
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - redis
  
volumes:
   mongoData: